# Generated by Django 4.0.3 on 2022-04-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0003_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('1', 'Published'), ('2', 'Unpublished')], default=2, max_length=2),
        ),
    ]
